/// Suggestions de catégories basées sur des mots-clés dans le libellé SG.
/// La suggestion est proposée à l'utilisateur qui peut la valider ou la changer.
class CategorySuggestionService {
  static const Map<String, List<String>> _keywords = {
    'Loyer': [
      'loyer',
      'bail',
      'immo',
      'immobilier',
      'habitation',
      'proprietaire',
      'locataire',
    ],
    'Abonnement': [
      'free',
      'sfr',
      'orange',
      'bouygues',
      'netflix',
      'spotify',
      'deezer',
      'amazon prime',
      'apple',
      'google',
      'microsoft',
      'ovh',
      'adobe',
      'canal',
      'disney',
      'youtube',
      'abonnement',
      'subscription',
      'prime',
    ],
    'Coffee': [
      'starbucks',
      'columbus',
      'cafe',
      'coffee',
      'expresso',
      'brioche doree',
      'paul ',
      'costa',
      'the ',
      'palais des thes',
      'tea',
      'salon de the',
    ],
    'Course': [
      'carrefour',
      'leclerc',
      'e.leclerc',
      'lidl',
      'aldi',
      'intermarche',
      'interm ',
      'franprix',
      'monoprix',
      'casino',
      'supermarche',
      'superette',
      'bio c bon',
      'naturalia',
      'biocoop',
      'picard',
      'thiriet',
      'g20',
      'ed ',
      'netto',
      'auchan',
      'cora',
      'super u',
      'simply',
      'market',
      'epicerie',
      'calao',
      'yasami',
      '3fm',
      'gbs ',
    ],
    'Loisirs': [
      'cinema',
      'cine ',
      'ugc',
      'pathe',
      'mk2',
      'gaumont',
      'fnac',
      'decathlon',
      'game',
      'steam',
      'playstation',
      'xbox',
      'nintendo',
      'musee',
      'exposition',
      'concert',
      'theatre',
      'spectacle',
      'parc',
      'loisirs',
      'bowling',
      'escape',
      'laser',
      'fabrik',
      'jeux',
    ],
    'Restaurant': [
      'restaurant',
      'mcdonald',
      'burger king',
      'quick',
      'kfc',
      'subway',
      'sushi',
      'pizza',
      'brasserie',
      'bistrot',
      'bistro',
      'kebab',
      'tacos',
      'noodle',
      'ramen',
      'trattoria',
      'pizzeria',
      'boulangerie',
      'patisserie',
      'five guys',
      'la brioche',
      'hippopotamus',
      'courtepaille',
      'buffalo',
      'flunch',
      'banh mi',
      'poke',
      'dumpling',
      'mao ',
      'sq *',
      'le ju',
      'yithe',
      'coeur de',
      'uber* eats',
      'uber eats',
      'uber   * eats',
      'carte ticket restaurant',
      'ticket restaurant',
    ],
    'Santé': [
      'pharmacie',
      'medecin',
      'docteur',
      'hopital',
      'clinique',
      'dentiste',
      'optique',
      'ophtalmo',
      'kiné',
      'kinesitherapeute',
      'sante',
      'mutuelle',
      'assurance maladie',
      'laboratoire',
      'analyses',
    ],
    'Shopping': [
      'zara',
      'h&m',
      'hm ',
      'uniqlo',
      'amazon',
      'vinted',
      'cdiscount',
      'darty',
      'fnac',
      'ikea',
      'leroy merlin',
      'brico',
      'decathlo',
      'nike',
      'adidas',
      'gap',
      'mango',
      'primark',
      'kiabi',
      'jules',
      'celio',
      'asos',
      'zalando',
      'shein',
      'aliexpress',
      'ebay',
      'leboncoin',
      'rakuten',
      'shopping',
      'boutique',
      'magasin',
    ],
    'Transports': [
      'sncf',
      'ratp',
      'metro',
      'taxi',
      'uber',
      'bolt',
      'kapten',
      'blablacar',
      'navigo',
      'velib',
      'lime',
      'bird ',
      'transilien',
      'ter ',
      'tgv',
      'ouigo',
      'eurostar',
      'thalys',
      'izy ',
      'transports',
      'parking',
      'peage',
      'autoroute',
      'essence',
      'total',
      'bp ',
      'shell',
      'esso',
      'station',
      'carburant',
      'flixbus',
      'ouibus',
      'xft ',
    ],
    'Voyage': [
      'hotel',
      'airbnb',
      'booking',
      'voyage',
      'avion',
      'air france',
      'easyjet',
      'ryanair',
      'volotea',
      'transavia',
      'lufthansa',
      'british',
      'iberia',
      'aeroport',
      'airport',
      'location voiture',
      'hertz',
      'avis ',
      'europcar',
      'sixt',
      'vrbo',
      'gites',
    ],
  };

  /// Retourne la catégorie suggérée ou null si aucune correspondance.
  static String? suggest(String rawLabel) {
    final lower = rawLabel.toLowerCase();

    // Règles prioritaires pour les cas ambigus multi-mots
    if (lower.contains('uber') && (lower.contains('eats') || lower.contains('eat'))) {
      return 'Restaurant';
    }
    if (lower.contains('ticket restaurant') || lower.contains('carte ticket')) {
      return 'Restaurant';
    }

    for (final entry in _keywords.entries) {
      for (final keyword in entry.value) {
        if (lower.contains(keyword)) return entry.key;
      }
    }
    return null;
  }
}

